### ISSUE TITLE
AIQUM 9.10 OS requirements is hard to read

### ISSUE THREAD

**Issue by zarantha2003** [NetAppDocs/active-iq-unified-manager-910#6]
Page: [Windows software and installation requirements](https://docs.netapp.com/us-en/active-iq-unified-manager-910/install-windows/reference_windows_software_and_installation_requirements.html)

The line:

You can install Unified Manager on the following Windows editions: * Microsoft Windows Server 2016 Standard and Datacenter Edition * Microsoft Windows Server 2019 Standard and Datacenter Edition

Should be the same as the 9.11 version, with actual bullet points and formatted as a list:

You can install Unified Manager on the following Windows editions:
    * Microsoft Windows Server 2019 Standard and Datacenter Edition
    * Microsoft Windows Server 2022 Standard and Datacenter Edition

**Comment by netapp-manini** [comment]
Thank you for your feedback. We will update the content to make sure it aligns with what you have suggested. We will update this issue with the links to the updated content and inform you.

**Comment by netapp-manini** [comment]
The bullets have been added at [Windows software and installation requirements](https://docs.netapp.com/us-en/active-iq-unified-manager-910/install-windows/reference_windows_software_and_installation_requirements.html)

Please check. Unless there are more comments, will close this issue.
