### ISSUE TITLE
Please add example locations for the exclusion directories

### ISSUE THREAD

**Issue by alexanderjacuna** [NetAppDocs/active-iq-unified-manager-910#7]
Page: [Windows software and installation requirements](https://docs.netapp.com/us-en/active-iq-unified-manager-910/install-windows/reference_windows_software_and_installation_requirements.html)

Unified Manager data directory
Unified Manager installation directory
MySQL data directory

These directories need example/default locations so that customers can get an idea of what they are looking for. The "SANscreen" directory is confusing to customers. The backup location might not be known; and the MySQL data directory might also be confusing when its nested within the installation directory.

**Comment by netapp-manini** [comment]
Thank you for your feedback. We will update the content to make sure it aligns with what you have suggested. We will update this issue with the links to the updated content and inform you.

**Comment by netapp-manini** [comment]
The sample paths have been added at [Windows software and installation requirements](https://docs.netapp.com/us-en/active-iq-unified-manager-910/install-windows/reference_windows_software_and_installation_requirements.html)

Please check. Unless there are more comments, will close this issue.
